version: 0.0
os: linux


files:
  - source: /ccwebapp/webapp/librarymanagementsystem/target/librarymanagementsystem-0.0.1-SNAPSHOT.war
    destination: /opt/tomcat/latest/webapps
  - source: ./infrastructure/aws/codedeploy/afterInstall.sh
    destination: /home/centos
  - source: ./infrastructure/aws/codedeploy/applicationStart.sh
    destination: /home/centos
hooks:
  AfterInstall:
   - location: ./afterInstall.sh
     timeout: 180
     runas: centos
  ApplicationStart:
   - location: ./applicationStart.sh
     timeout: 180
     runas: centos
