version: 2
jobs:
  build:
    branches:
      only:
        - assignment5
    docker:
      - image: circleci/python:2.7-jessie
    steps:
      - checkout
      - run:
          name: Install packages
          command: sudo apt-get update && sudo apt-get install wget zip unzip -y
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Build Artifact
          command: |
            cd webapp
            pwd
            ls -al
            mvn clean install
            cd target/
            ls -al
            cd ../
            pwd
            ls -al
      - run:
          name: Zip Artifact
          command: |
            echo "current build number is ${CIRCLE_BUILD_NUM}"
            pwd
            mkdir -p codedeploy_artifact
            cd codedeploy_artifact
            cp ../infrastructure/aws/codedeploy/*.sh .
            cp ../*.yml .
            cp ../webapp/target/webApp-0.0.1-SNAPSHOT.jar .
            cp ../webapp/src/main/resources/*.properties .
            zip -r csye6225-web-app-${CIRCLE_BUILD_NUM}.zip .
            rm *.yml *.sh *.properties *.jar
            ls -al
            pwd
            cd ..
            pwd
            ls -al
